logging:
  level: INFO
  loggers:
    com.engage.expenses: INFO

server:
  rootPath: /api/*

database:
  driverClass: org.postgresql.Driver
  user: engage
  password: engage
  url: jdbc:postgresql://192.168.99.100:32768/expenses
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

dateFormat: yyyy-MM-dd'T'HH:mmZ
